DisablePathCorrection: false
EnablePathEscape: false
FireMethodNotAllowed: true
DisableBodyConsumptionOnUnmarshal: true
TimeFormat: Mon, 01 Jan 2006 15:04:05 GMT
Charset: UTF-8

Other:
  log-level : error
  port : "8080"
  build_interval: 180
  mysql-dsn: lookup:lookup@2019@tcp(127.0.0.1:3306)/mixer?charset=utf8&parseTime=True&loc=Local&timeout=10s&readTimeout=30s&writeTimeout=60s
  mysql-max-idle: 20
  mysql-max-open: 50
  mysql-maxlifetime: 120
  mysql-log-mode: true
  kube-config-dir : /etc/kube
  key: xsyxxsyxxsyxxsyx
  catalog-concurrency : 1000
#  image-repository-domain: harbor.xsts.xyz
  log-path: /var/log/niwo/
  swagger-ip: 172.21.101.228
  qps: 20000
  bucket-size: 50000

  # storage mysql -h 127.0.0.1 -P 3306 -ulookup -plookup@2019
  #mysql-dev: root:Root!@#Toor@tcp(120.24.144.110:3306)/niwo?charset=utf8&parseTime=True&loc=Local&timeout=10s&readTimeout=30s&writeTimeout=60s
  mysql-dev: root:root@tcp(localhost:3306)/niwo?charset=utf8&parseTime=True&loc=Local&timeout=10s&readTimeout=30s&writeTimeout=60s
#    ip:
#    port:
#    user:
#    passwd:
#    storage:

  mysql-pro:
#    ip:
#    port:
#    user:
#    passwd:
#    storage:

##mongo 127.0.0.1:27017
  #mongodb-dev: mongodb://120.24.144.110:27017
  mongodb-dev: mongodb://127.0.0.1:27017
  mongo-dev-database: niwo
  mongo-dev-collection: demo
  mongodb-pro: