// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/catalog/economicsRecordList": {
            "get": {
                "description": "获取\"经济\"分类的纪录主题列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "description": "param",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.GetEconomicsRecordListReq"
                        }
                    }
                ],
                "responses": {
                    "20000": {
                        "schema": {
                            "$ref": "#/definitions/github.com_hfeng101_niwo_controller_catalog_v1.ResponseContent"
                        }
                    },
                    "50001": {
                        "schema": {
                            "$ref": "#/definitions/github.com_hfeng101_niwo_controller_catalog_v1.ResponseContent"
                        }
                    }
                }
            }
        },
        "/catalog/entertainmentRecordList": {
            "get": {
                "description": "获取\"娱乐\"分类的纪录主题列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "description": "param",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.GetEntertainmentRecordListReq"
                        }
                    }
                ],
                "responses": {
                    "20000": {
                        "schema": {
                            "$ref": "#/definitions/github.com_hfeng101_niwo_controller_catalog_v1.ResponseContent"
                        }
                    },
                    "50001": {
                        "schema": {
                            "$ref": "#/definitions/github.com_hfeng101_niwo_controller_catalog_v1.ResponseContent"
                        }
                    }
                }
            }
        },
        "/catalog/list": {
            "get": {
                "description": "获取指定分类的纪录主题列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "description": "param",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.GetRecordListReq"
                        }
                    }
                ],
                "responses": {
                    "20000": {
                        "schema": {
                            "$ref": "#/definitions/github.com_hfeng101_niwo_controller_catalog_v1.ResponseContent"
                        }
                    },
                    "50001": {
                        "schema": {
                            "$ref": "#/definitions/github.com_hfeng101_niwo_controller_catalog_v1.ResponseContent"
                        }
                    }
                }
            }
        },
        "/catalog/listByKey": {
            "get": {
                "description": "根据搜索获取关键字对应的主题列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "description": "param",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.GetRecordListByKeywordReq"
                        }
                    }
                ],
                "responses": {
                    "20000": {
                        "schema": {
                            "$ref": "#/definitions/github.com_hfeng101_niwo_controller_catalog_v1.ResponseContent"
                        }
                    },
                    "50001": {
                        "schema": {
                            "$ref": "#/definitions/github.com_hfeng101_niwo_controller_catalog_v1.ResponseContent"
                        }
                    }
                }
            }
        },
        "/catalog/militaryRecordList": {
            "get": {
                "description": "获取\"军事\"分类的纪录主题列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "description": "param",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.GetMilitaryRecordListReq"
                        }
                    }
                ],
                "responses": {
                    "20000": {
                        "schema": {
                            "$ref": "#/definitions/github.com_hfeng101_niwo_controller_catalog_v1.ResponseContent"
                        }
                    },
                    "50001": {
                        "schema": {
                            "$ref": "#/definitions/github.com_hfeng101_niwo_controller_catalog_v1.ResponseContent"
                        }
                    }
                }
            }
        },
        "/catalog/personageRecordList": {
            "get": {
                "description": "获取\"人物\"分类的纪录主题列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "description": "param",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.GetPersonageRecordListReq"
                        }
                    }
                ],
                "responses": {
                    "20000": {
                        "schema": {
                            "$ref": "#/definitions/github.com_hfeng101_niwo_controller_catalog_v1.ResponseContent"
                        }
                    },
                    "50001": {
                        "schema": {
                            "$ref": "#/definitions/github.com_hfeng101_niwo_controller_catalog_v1.ResponseContent"
                        }
                    }
                }
            }
        },
        "/catalog/sportRecordList": {
            "get": {
                "description": "获取\"体育\"分类的纪录主题列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "description": "param",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.GetSportRecordListReq"
                        }
                    }
                ],
                "responses": {
                    "20000": {
                        "schema": {
                            "$ref": "#/definitions/github.com_hfeng101_niwo_controller_catalog_v1.ResponseContent"
                        }
                    },
                    "50001": {
                        "schema": {
                            "$ref": "#/definitions/github.com_hfeng101_niwo_controller_catalog_v1.ResponseContent"
                        }
                    }
                }
            }
        },
        "/content/getReferenceFile": {
            "get": {
                "description": "用户获取图片、音、视频文件",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "description": "param",
                        "name": "Param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.GetReferenceFileReq"
                        }
                    }
                ],
                "responses": {
                    "20000": {
                        "schema": {
                            "$ref": "#/definitions/github.com_hfeng101_niwo_controller_content_v1.ResponseContent"
                        }
                    },
                    "50001": {
                        "schema": {
                            "$ref": "#/definitions/github.com_hfeng101_niwo_controller_content_v1.ResponseContent"
                        }
                    }
                }
            }
        },
        "/content/theme": {
            "get": {
                "description": "获取指定主题的具体内容",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "description": "param",
                        "name": "Param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.GetContentReq"
                        }
                    }
                ],
                "responses": {
                    "20000": {
                        "schema": {
                            "$ref": "#/definitions/github.com_hfeng101_niwo_controller_content_v1.ResponseContent"
                        }
                    },
                    "50001": {
                        "schema": {
                            "$ref": "#/definitions/github.com_hfeng101_niwo_controller_content_v1.ResponseContent"
                        }
                    }
                }
            },
            "put": {
                "description": "用户编辑更新内容",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "description": "param",
                        "name": "Param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.UpdateContentReq"
                        }
                    }
                ],
                "responses": {
                    "20000": {
                        "schema": {
                            "$ref": "#/definitions/github.com_hfeng101_niwo_controller_content_v1.ResponseContent"
                        }
                    },
                    "50001": {
                        "schema": {
                            "$ref": "#/definitions/github.com_hfeng101_niwo_controller_content_v1.ResponseContent"
                        }
                    }
                }
            },
            "post": {
                "description": "用户创作主题及对应内容",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "description": "param",
                        "name": "Param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.AddContentReq"
                        }
                    }
                ],
                "responses": {
                    "20000": {
                        "schema": {
                            "$ref": "#/definitions/github.com_hfeng101_niwo_controller_content_v1.ResponseContent"
                        }
                    },
                    "50001": {
                        "schema": {
                            "$ref": "#/definitions/github.com_hfeng101_niwo_controller_content_v1.ResponseContent"
                        }
                    }
                }
            }
        },
        "/content/uploadFile": {
            "post": {
                "description": "用户上传图片、音、视频文件",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "description": "param",
                        "name": "Param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.UpdateContentReq"
                        }
                    }
                ],
                "responses": {
                    "20000": {
                        "schema": {
                            "$ref": "#/definitions/github.com_hfeng101_niwo_controller_content_v1.ResponseContent"
                        }
                    },
                    "50001": {
                        "schema": {
                            "$ref": "#/definitions/github.com_hfeng101_niwo_controller_content_v1.ResponseContent"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "获取到验证码后，验证登录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "description": "param",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.UserRegistrationOrLoginReq"
                        }
                    }
                ],
                "responses": {
                    "20000": {
                        "schema": {
                            "$ref": "#/definitions/github.com_hfeng101_niwo_controller_user_v1.ResponseContent"
                        }
                    },
                    "50001": {
                        "schema": {
                            "$ref": "#/definitions/github.com_hfeng101_niwo_controller_user_v1.ResponseContent"
                        }
                    }
                }
            }
        },
        "/login/getVerificationCode": {
            "post": {
                "description": "用户登录，获取验证码，若是第一次登陆则自动注册",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "description": "param",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.GetVerificationCodeReq"
                        }
                    }
                ],
                "responses": {
                    "20000": {
                        "schema": {
                            "$ref": "#/definitions/github.com_hfeng101_niwo_controller_user_v1.ResponseContent"
                        }
                    },
                    "50001": {
                        "schema": {
                            "$ref": "#/definitions/github.com_hfeng101_niwo_controller_user_v1.ResponseContent"
                        }
                    }
                }
            }
        },
        "/login/updateToken": {
            "post": {
                "description": "用户token过期，重复更新",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "description": "param",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.UpdateTokenReq"
                        }
                    }
                ],
                "responses": {
                    "20000": {
                        "schema": {
                            "$ref": "#/definitions/github.com_hfeng101_niwo_controller_user_v1.ResponseContent"
                        }
                    },
                    "50001": {
                        "schema": {
                            "$ref": "#/definitions/github.com_hfeng101_niwo_controller_user_v1.ResponseContent"
                        }
                    }
                }
            }
        },
        "/login/verifyLogin": {
            "post": {
                "description": "验证用户以前登陆所生成的token来验证登陆",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "description": "param",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.VerifyLoginReq"
                        }
                    }
                ],
                "responses": {
                    "20000": {
                        "schema": {
                            "$ref": "#/definitions/github.com_hfeng101_niwo_controller_user_v1.ResponseContent"
                        }
                    },
                    "50001": {
                        "schema": {
                            "$ref": "#/definitions/github.com_hfeng101_niwo_controller_user_v1.ResponseContent"
                        }
                    }
                }
            }
        },
        "/logout": {
            "post": {
                "description": "用户退出，清除所有登录状态",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "description": "param",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.LogoutReq"
                        }
                    }
                ],
                "responses": {
                    "20000": {
                        "schema": {
                            "$ref": "#/definitions/github.com_hfeng101_niwo_controller_user_v1.ResponseContent"
                        }
                    },
                    "50001": {
                        "schema": {
                            "$ref": "#/definitions/github.com_hfeng101_niwo_controller_user_v1.ResponseContent"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github.com_hfeng101_niwo_controller_catalog_v1.ResponseContent": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "object"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "github.com_hfeng101_niwo_controller_content_v1.ResponseContent": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "object"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "github.com_hfeng101_niwo_controller_user_v1.ResponseContent": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "object"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "v1.AddContentReq": {
            "type": "object",
            "properties": {
                "catalogType": {
                    "type": "string"
                },
                "content": {
                    "type": "string"
                },
                "keyword": {
                    "type": "string"
                },
                "theme": {
                    "type": "string"
                }
            }
        },
        "v1.GetContentReq": {
            "type": "object",
            "properties": {
                "catalogType": {
                    "type": "string"
                },
                "theme": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "v1.GetEconomicsRecordListReq": {
            "type": "object"
        },
        "v1.GetEntertainmentRecordListReq": {
            "type": "object"
        },
        "v1.GetMilitaryRecordListReq": {
            "type": "object"
        },
        "v1.GetPersonageRecordListReq": {
            "type": "object"
        },
        "v1.GetRecordListByKeywordReq": {
            "type": "object",
            "properties": {
                "keyword": {
                    "type": "string"
                }
            }
        },
        "v1.GetRecordListReq": {
            "type": "object"
        },
        "v1.GetReferenceFileReq": {
            "type": "object"
        },
        "v1.GetSportRecordListReq": {
            "type": "object"
        },
        "v1.GetVerificationCodeReq": {
            "type": "object",
            "properties": {
                "phoneNumber": {
                    "type": "string"
                }
            }
        },
        "v1.LogoutReq": {
            "type": "object",
            "properties": {
                "phoneNumber": {
                    "type": "string"
                }
            }
        },
        "v1.UpdateContentReq": {
            "type": "object",
            "properties": {
                "catalogType": {
                    "type": "string"
                },
                "content": {
                    "type": "string"
                },
                "keyword": {
                    "type": "string"
                },
                "theme": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "v1.UpdateTokenReq": {
            "type": "object",
            "properties": {
                "freshToken": {
                    "type": "string"
                },
                "phoneNumber": {
                    "type": "string"
                }
            }
        },
        "v1.UserRegistrationOrLoginReq": {
            "type": "object",
            "properties": {
                "phoneNumber": {
                    "description": "Name string ` + "`" + `json:\"name\"` + "`" + `\nEmail string ` + "`" + `json:\"email\"` + "`" + `",
                    "type": "string"
                },
                "verificationCode": {
                    "description": "Password string ` + "`" + `json:\"password\"` + "`" + `",
                    "type": "string"
                }
            }
        },
        "v1.VerifyLoginReq": {
            "type": "object",
            "properties": {
                "phoneNumber": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
