definitions:
  github.com_hfeng101_niwo_controller_catalog_v1.ResponseContent:
    properties:
      code:
        type: integer
      data:
        type: object
      message:
        type: string
    type: object
  github.com_hfeng101_niwo_controller_content_v1.ResponseContent:
    properties:
      code:
        type: integer
      data:
        type: object
      message:
        type: string
    type: object
  github.com_hfeng101_niwo_controller_user_v1.ResponseContent:
    properties:
      code:
        type: integer
      data:
        type: object
      message:
        type: string
    type: object
  v1.AddContentReq:
    properties:
      catalogType:
        type: string
      content:
        type: string
      keyword:
        type: string
      theme:
        type: string
    type: object
  v1.GetRecordListByKeywordReq:
    properties:
      catalog:
        type: string
      keyword:
        type: string
    type: object
  v1.GetVerificationCodeReq:
    properties:
      phoneNumber:
        type: string
    type: object
  v1.LogoutReq:
    properties:
      phoneNumber:
        type: string
    type: object
  v1.UpdateContentReq:
    properties:
      catalogType:
        type: string
      content:
        type: string
      keyword:
        type: string
      theme:
        type: string
      uuid:
        type: string
    type: object
  v1.UpdateTokenReq:
    properties:
      freshToken:
        type: string
      phoneNumber:
        type: string
    type: object
  v1.UploadFileReq:
    properties:
      catalog:
        type: string
      name:
        type: string
      type:
        description: 类型有file/picture/short-video/long-video/audio
        type: string
    type: object
  v1.UserRegistrationOrLoginReq:
    properties:
      phoneNumber:
        description: |-
          Name string `json:"name"`
          Email string `json:"email"`
        type: string
      verificationCode:
        description: Password string `json:"password"`
        type: string
    type: object
  v1.VerifyLoginReq:
    properties:
      phoneNumber:
        type: string
      token:
        type: string
    type: object
info:
  contact: {}
paths:
  /v1/catalog/economicsRecordList:
    get:
      consumes:
      - application/json
      description: 获取"经济"分类的纪录主题列表
      produces:
      - application/json
      responses:
        "20000":
          schema:
            $ref: '#/definitions/github.com_hfeng101_niwo_controller_catalog_v1.ResponseContent'
        "50001":
          schema:
            $ref: '#/definitions/github.com_hfeng101_niwo_controller_catalog_v1.ResponseContent'
  /v1/catalog/entertainmentRecordList:
    get:
      consumes:
      - application/json
      description: 获取"娱乐"分类的纪录主题列表
      produces:
      - application/json
      responses:
        "20000":
          schema:
            $ref: '#/definitions/github.com_hfeng101_niwo_controller_catalog_v1.ResponseContent'
        "50001":
          schema:
            $ref: '#/definitions/github.com_hfeng101_niwo_controller_catalog_v1.ResponseContent'
  /v1/catalog/list:
    get:
      consumes:
      - application/json
      description: 获取指定分类的纪录主题列表
      parameters:
      - description: param
        in: query
        name: catalog
        required: true
        type: string
      produces:
      - application/json
      responses:
        "20000":
          schema:
            $ref: '#/definitions/github.com_hfeng101_niwo_controller_catalog_v1.ResponseContent'
        "50001":
          schema:
            $ref: '#/definitions/github.com_hfeng101_niwo_controller_catalog_v1.ResponseContent'
  /v1/catalog/listByKey:
    post:
      consumes:
      - application/json
      description: 根据搜索获取关键字对应的主题列表
      parameters:
      - description: param
        in: body
        name: param
        required: true
        schema:
          $ref: '#/definitions/v1.GetRecordListByKeywordReq'
      produces:
      - application/json
      responses:
        "20000":
          schema:
            $ref: '#/definitions/github.com_hfeng101_niwo_controller_catalog_v1.ResponseContent'
        "50001":
          schema:
            $ref: '#/definitions/github.com_hfeng101_niwo_controller_catalog_v1.ResponseContent'
  /v1/catalog/militaryRecordList:
    get:
      consumes:
      - application/json
      description: 获取"军事"分类的纪录主题列表
      produces:
      - application/json
      responses:
        "20000":
          schema:
            $ref: '#/definitions/github.com_hfeng101_niwo_controller_catalog_v1.ResponseContent'
        "50001":
          schema:
            $ref: '#/definitions/github.com_hfeng101_niwo_controller_catalog_v1.ResponseContent'
  /v1/catalog/personageRecordList:
    get:
      consumes:
      - application/json
      description: 获取"人物"分类的纪录主题列表
      produces:
      - application/json
      responses:
        "20000":
          schema:
            $ref: '#/definitions/github.com_hfeng101_niwo_controller_catalog_v1.ResponseContent'
        "50001":
          schema:
            $ref: '#/definitions/github.com_hfeng101_niwo_controller_catalog_v1.ResponseContent'
  /v1/catalog/sportRecordList:
    get:
      consumes:
      - application/json
      description: 获取"体育"分类的纪录主题列表
      produces:
      - application/json
      responses:
        "20000":
          schema:
            $ref: '#/definitions/github.com_hfeng101_niwo_controller_catalog_v1.ResponseContent'
        "50001":
          schema:
            $ref: '#/definitions/github.com_hfeng101_niwo_controller_catalog_v1.ResponseContent'
  /v1/content/getReferenceFile:
    get:
      consumes:
      - application/json
      description: 用户获取图片、音、视频文件
      parameters:
      - description: param
        in: query
        name: objectKey
        required: true
        type: string
      produces:
      - application/json
      responses:
        "20000":
          schema:
            $ref: '#/definitions/github.com_hfeng101_niwo_controller_content_v1.ResponseContent'
        "50001":
          schema:
            $ref: '#/definitions/github.com_hfeng101_niwo_controller_content_v1.ResponseContent'
  /v1/content/theme:
    get:
      consumes:
      - application/json
      description: 获取指定主题的具体内容
      parameters:
      - description: param
        in: query
        name: catalog
        required: true
        type: string
      - description: param
        in: query
        name: theme
        required: true
        type: string
      - description: param
        in: query
        name: uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "20000":
          schema:
            $ref: '#/definitions/github.com_hfeng101_niwo_controller_content_v1.ResponseContent'
        "50001":
          schema:
            $ref: '#/definitions/github.com_hfeng101_niwo_controller_content_v1.ResponseContent'
    post:
      consumes:
      - application/json
      description: 用户创作主题及对应内容
      parameters:
      - description: param
        in: body
        name: Param
        required: true
        schema:
          $ref: '#/definitions/v1.AddContentReq'
      produces:
      - application/json
      responses:
        "20000":
          schema:
            $ref: '#/definitions/github.com_hfeng101_niwo_controller_content_v1.ResponseContent'
        "50001":
          schema:
            $ref: '#/definitions/github.com_hfeng101_niwo_controller_content_v1.ResponseContent'
    put:
      consumes:
      - application/json
      description: 用户编辑更新内容
      parameters:
      - description: param
        in: body
        name: Param
        required: true
        schema:
          $ref: '#/definitions/v1.UpdateContentReq'
      produces:
      - application/json
      responses:
        "20000":
          schema:
            $ref: '#/definitions/github.com_hfeng101_niwo_controller_content_v1.ResponseContent'
        "50001":
          schema:
            $ref: '#/definitions/github.com_hfeng101_niwo_controller_content_v1.ResponseContent'
  /v1/content/uploadFile:
    post:
      consumes:
      - application/json
      description: 用户上传图片、音、视频文件
      parameters:
      - description: param
        in: body
        name: Param
        required: true
        schema:
          $ref: '#/definitions/v1.UploadFileReq'
      produces:
      - application/json
      responses:
        "20000":
          schema:
            $ref: '#/definitions/github.com_hfeng101_niwo_controller_content_v1.ResponseContent'
        "50001":
          schema:
            $ref: '#/definitions/github.com_hfeng101_niwo_controller_content_v1.ResponseContent'
  /v1/login:
    post:
      consumes:
      - application/json
      description: 获取到验证码后，通过验证码登录
      parameters:
      - description: param
        in: body
        name: param
        required: true
        schema:
          $ref: '#/definitions/v1.UserRegistrationOrLoginReq'
      produces:
      - application/json
      responses:
        "20000":
          schema:
            $ref: '#/definitions/github.com_hfeng101_niwo_controller_user_v1.ResponseContent'
        "50001":
          schema:
            $ref: '#/definitions/github.com_hfeng101_niwo_controller_user_v1.ResponseContent'
  /v1/login/getVerificationCode:
    post:
      consumes:
      - application/json
      description: 用户登录，获取验证码，若是第一次登陆则自动注册
      parameters:
      - description: param
        in: body
        name: param
        required: true
        schema:
          $ref: '#/definitions/v1.GetVerificationCodeReq'
      produces:
      - application/json
      responses:
        "20000":
          schema:
            $ref: '#/definitions/github.com_hfeng101_niwo_controller_user_v1.ResponseContent'
        "50001":
          schema:
            $ref: '#/definitions/github.com_hfeng101_niwo_controller_user_v1.ResponseContent'
  /v1/login/updateToken:
    post:
      consumes:
      - application/json
      description: 用户token过期，重复更新
      parameters:
      - description: param
        in: body
        name: param
        required: true
        schema:
          $ref: '#/definitions/v1.UpdateTokenReq'
      produces:
      - application/json
      responses:
        "20000":
          schema:
            $ref: '#/definitions/github.com_hfeng101_niwo_controller_user_v1.ResponseContent'
        "50001":
          schema:
            $ref: '#/definitions/github.com_hfeng101_niwo_controller_user_v1.ResponseContent'
  /v1/login/verifyLogin:
    post:
      consumes:
      - application/json
      description: 验证用户以前登陆所生成的token来验证登陆
      parameters:
      - description: param
        in: body
        name: param
        required: true
        schema:
          $ref: '#/definitions/v1.VerifyLoginReq'
      produces:
      - application/json
      responses:
        "20000":
          schema:
            $ref: '#/definitions/github.com_hfeng101_niwo_controller_user_v1.ResponseContent'
        "50001":
          schema:
            $ref: '#/definitions/github.com_hfeng101_niwo_controller_user_v1.ResponseContent'
  /v1/logout:
    post:
      consumes:
      - application/json
      description: 用户退出，清除所有登录状态
      parameters:
      - description: param
        in: body
        name: param
        required: true
        schema:
          $ref: '#/definitions/v1.LogoutReq'
      produces:
      - application/json
      responses:
        "20000":
          schema:
            $ref: '#/definitions/github.com_hfeng101_niwo_controller_user_v1.ResponseContent'
        "50001":
          schema:
            $ref: '#/definitions/github.com_hfeng101_niwo_controller_user_v1.ResponseContent'
swagger: "2.0"
